CREATE TABLE usuarios (
	id INT PRIMARY KEY AUTO_INCREMENT,
	userName VARCHAR(128) NOT NULL,
	senha VARCHAR(128) NOT NULL,
	dataCriacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	ativo BOOLEAN NOT NULL DEFAULT true
);